import type { PrIdentifier, PrInfo, PrComment, CommentStatus } from './types.js';

interface AdoPr {
  title: string;
  description: string;
  createdBy: { displayName: string; uniqueName: string };
  sourceRefName: string; // refs/heads/feature/foo
  targetRefName: string; // refs/heads/main
  status: string; // active, completed, abandoned
  url: string;
}

interface AdoThread {
  id: number;
  status: string; // active, fixed, wontFix, closed, byDesign, pending
  threadContext?: {
    filePath: string;
    rightFileStart?: { line: number };
    leftFileStart?: { line: number };
  };
  comments: AdoThreadComment[];
}

interface AdoThreadComment {
  id: number;
  author: { displayName: string; uniqueName: string };
  content: string;
  commentType: string; // text, system
  publishedDate: string;
  lastUpdatedDate: string;
}

function mapAdoStatus(status: string): CommentStatus {
  switch (status) {
    case 'active':
    case 'pending':
      return 'active';
    case 'fixed':
    case 'byDesign':
      return 'resolved';
    case 'wontFix':
      return "won't fix";
    case 'closed':
      return 'closed';
    default:
      return 'active';
  }
}

async function adoFetch<T>(url: string, token: string): Promise<T> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };
  if (token) {
    headers['Authorization'] = `Basic ${Buffer.from(`:${token}`).toString('base64')}`;
  }

  const res = await fetch(url, { headers, redirect: 'manual' });

  // A redirect means ADO is sending us to a login page — PAT is missing/invalid
  if (res.status >= 300 && res.status < 400) {
    const location = res.headers.get('location') ?? '(none)';
    throw new Error(`Azure DevOps API redirected (${res.status}) to ${location}. The PAT is likely missing, expired, or lacks the required scope.`);
  }

  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`Azure DevOps API ${res.status}: ${url} — ${body.slice(0, 200)}`);
  }

  const contentType = res.headers.get('content-type') ?? '';
  if (!contentType.includes('application/json')) {
    const body = await res.text().catch(() => '');
    throw new Error(`Azure DevOps API returned non-JSON (${contentType || 'no content-type'}). The PAT may be missing or expired. Response: ${body.slice(0, 200)}`);
  }

  return res.json() as Promise<T>;
}

function stripRefPrefix(ref: string): string {
  return ref.replace(/^refs\/heads\//, '');
}

/**
 * Fetch PR metadata and all comment threads from Azure DevOps.
 */
export async function fetchDevOpsPr(pr: PrIdentifier, token: string): Promise<PrInfo> {
  if (!pr.project) {
    throw new Error('Azure DevOps PR requires a project name');
  }

  const baseApi = `https://dev.azure.com/${pr.owner}/${pr.project}/_apis/git/repositories/${pr.repo}/pullRequests/${pr.prNumber}`;
  const apiVersion = 'api-version=7.0';

  const [prData, threadsData] = await Promise.all([
    adoFetch<AdoPr>(`${baseApi}?${apiVersion}`, token),
    adoFetch<{ value: AdoThread[] }>(`${baseApi}/threads?${apiVersion}`, token),
  ]);

  const prUrl = `https://dev.azure.com/${pr.owner}/${pr.project}/_git/${pr.repo}/pullrequest/${pr.prNumber}`;

  const comments: PrComment[] = [];

  for (const thread of threadsData.value) {
    // Skip system threads (auto-generated by status changes, policies, etc.)
    const humanComments = thread.comments.filter((c) => c.commentType !== 'system');
    if (humanComments.length === 0) continue;

    const first = humanComments[0]!;
    const rest = humanComments.slice(1);

    const filePath = thread.threadContext?.filePath;
    const lineNumber =
      thread.threadContext?.rightFileStart?.line ??
      thread.threadContext?.leftFileStart?.line ??
      undefined;

    const rootComment: PrComment = {
      id: `thread-${thread.id}`,
      author: first.author.displayName,
      body: first.content,
      status: mapAdoStatus(thread.status),
      createdAt: first.publishedDate,
      updatedAt: first.lastUpdatedDate,
      ...(filePath !== undefined ? { filePath } : {}),
      ...(lineNumber !== undefined ? { lineNumber } : {}),
      replies: rest.map((r) => ({
        id: `thread-${thread.id}-${r.id}`,
        author: r.author.displayName,
        body: r.content,
        status: mapAdoStatus(thread.status) as CommentStatus,
        createdAt: r.publishedDate,
        updatedAt: r.lastUpdatedDate,
      })),
    };

    comments.push(rootComment);
  }

  return {
    title: prData.title,
    description: prData.description ?? '',
    author: prData.createdBy.displayName,
    url: prUrl,
    sourceBranch: stripRefPrefix(prData.sourceRefName),
    targetBranch: stripRefPrefix(prData.targetRefName),
    status: prData.status,
    comments,
  };
}
