/**
 * Lightweight client for the Prism context REST API.
 * Fetches architecture overviews (and potentially other context types)
 * to pre-seed agent sessions with codebase understanding.
 */

export interface PrismConfig {
  /** Base URL of the Prism instance, e.g. "https://prism.example.com" */
  url: string;
  /** Bearer token for Prism API auth */
  apiKey: string;
}

export interface PrismContextSection {
  heading: string;
  priority: number;
  content: string;
  tokenCount: number;
}

export interface PrismContextResponse {
  sections: PrismContextSection[];
  totalTokens: number;
  truncated: boolean;
}

const REQUEST_TIMEOUT_MS = 8_000;

/**
 * Fetch the architecture overview for a project from Prism.
 * Returns null on any failure (network, auth, missing project, timeout).
 */
export async function fetchArchitectureContext(
  config: PrismConfig,
  slug: string,
  maxTokens = 6000,
): Promise<PrismContextResponse | null> {
  const url = `${config.url.replace(/\/+$/, '')}/api/projects/${slug}/context/arch`;

  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${config.apiKey}`,
      },
      body: JSON.stringify({ maxTokens }),
      signal: controller.signal,
    });

    clearTimeout(timer);

    if (!res.ok) {
      console.warn('[prism] arch context request failed: %d %s (slug=%s)', res.status, res.statusText, slug);
      return null;
    }

    return (await res.json()) as PrismContextResponse;
  } catch (err) {
    if (err instanceof Error && err.name === 'AbortError') {
      console.warn('[prism] arch context request timed out after %dms (slug=%s)', REQUEST_TIMEOUT_MS, slug);
    } else {
      console.warn('[prism] arch context request error (slug=%s):', slug, err);
    }
    return null;
  }
}

/**
 * Format a Prism context response into a markdown section suitable for CLAUDE.md.
 * Returns empty string if response is null or has no sections.
 */
export function formatPrismContext(response: PrismContextResponse | null): string {
  if (!response || response.sections.length === 0) return '';

  const parts: string[] = [
    '',
    '# Codebase Architecture (from Prism)',
    '',
    'The following architecture overview was auto-generated by Prism\'s codebase analysis.',
    'Use this as grounding context — it may be slightly stale relative to the current branch.',
    '',
  ];

  // Sort by priority (1 = most important) then append each section
  const sorted = [...response.sections].sort((a, b) => a.priority - b.priority);
  for (const section of sorted) {
    parts.push(`## ${section.heading}`, '', section.content, '');
  }

  if (response.truncated) {
    parts.push('> *Note: this overview was truncated to fit the token budget. Use the Prism MCP tools for deeper exploration.*', '');
  }

  return parts.join('\n');
}
